language: python

python:
  - "3.6"

cache:
  pip: true

install:
  - sudo apt-get update -q
  - sudo apt-get install libsodium-dev -y
  - pip install pytest pytezos

script:
  - pytest . -v

deploy:
  provider: script
  skip_cleanup: true
  script: pytezos deploy $TRAVIS_BUILD_DIR/src/atomex.tz --github-repo-slug="$TRAVIS_REPO_SLUG" --github-oauth-token="$GH_TOKEN"
  on:
    branch: master
    tags: true

